chore: write automated test for ockam examples

diff --git a/examples/command/portals/kafka/aiven/application_team/docker-compose.yml b/examples/command/portals/kafka/aiven/application_team/docker-compose.yml
--- a/examples/command/portals/kafka/aiven/application_team/docker-compose.yml
+++ b/examples/command/portals/kafka/aiven/application_team/docker-compose.yml
@@ -12,6 +12,8 @@ services:
     build:
       context: .
       dockerfile: ../kafka_ockam.dockerfile
+      args:
+        OCKAM_VERSION: ${OCKAM_VERSION:-latest}
     environment:
       ENROLLMENT_TICKET: ${CONSUMER_ENROLLMENT_TICKET:-}
       KAFKA_CLUSTER_API_KEY: ${KAFKA_CLUSTER_API_KEY:-}
@@ -30,10 +32,13 @@ services:
           echo "Press Ctrl+C to stop the container at any time, then execute "\
           "'./run.sh cleanup' to remove all containers.";
           echo "";
-          kafka-console-consumer.sh --topic demo --bootstrap-server 127.0.0.1:9092 --consumer.config kafka.config --max-messages 8;
-          if [ "$?" == "0" ]; then
-            echo "The example run was successful 🥳";
+          kafka-console-consumer.sh --topic demo --timeout-ms 50000 --bootstrap-server 127.0.0.1:9092 --consumer.config kafka.config --max-messages 8 | tee output.txt;
+          if [[ ! -s output.txt ]]; then
+            echo "Failed to receive messages";
+            exit 1;
           fi;
+
+          echo "The example run was successful 🥳.";
           echo "Messages received successfully, please Ctrl+C to exit";
           tail -f /dev/null;
         )
diff --git a/examples/command/portals/kafka/instaclustr/docker/application_team/docker-compose.yml b/examples/command/portals/kafka/instaclustr/docker/application_team/docker-compose.yml
--- a/examples/command/portals/kafka/instaclustr/docker/application_team/docker-compose.yml
+++ b/examples/command/portals/kafka/instaclustr/docker/application_team/docker-compose.yml
@@ -12,6 +12,8 @@ services:
     build:
       context: .
       dockerfile: kafka_client.dockerfile
+      args:
+        OCKAM_VERSION: ${OCKAM_VERSION:-latest}
     environment:
       ENROLLMENT_TICKET: ${CONSUMER_ENROLLMENT_TICKET:-}
       OCKAM_DEVELOPER: ${OCKAM_DEVELOPER:-false}
@@ -28,12 +30,14 @@ services:
           echo "=======================================================================";
           echo "Press Ctrl+C to stop the container at any time, then execute './run.sh cleanup' to remove all containers.";
           echo "";
-          kafka-console-consumer.sh --topic demo --bootstrap-server 127.0.0.1:9092 --consumer.config kafka.config --max-messages 8;
-          if [ "$?" -eq 0 ]; then
-            echo "Messages received successfully";
-            echo "The example run was successful 🥳";
-            echo "The consumer was able to decrypt messages, Instaclustr only saw encrypted messages";
+          kafka-console-consumer.sh --topic demo --timeout-ms 50000 --bootstrap-server 127.0.0.1:9092 --consumer.config kafka.config --max-messages 8 | tee output.txt;
+          if [[ ! -s output.txt ]]; then
+            echo "Failed to receive messages";
+            exit 1;
           fi;
+          echo "Messages received successfully";
+          echo "The example run was successful 🥳.";
+          echo "The consumer was able to decrypt messages, Instaclustr only saw encrypted messages";
           echo "Messages received successfully, please Ctrl+C to exit";
           tail -f /dev/null;
         )
