ci: combine commitlint, cla check and signatures check into one workflow

diff --git a/.github/workflows/commits.yml b/.github/workflows/commits.yml
--- a/.github/workflows/commits.yml
+++ b/.github/workflows/commits.yml
@@ -3,54 +3,101 @@ name: Commits
 permissions:
   contents: read
 
-on: [pull_request, push, workflow_dispatch]
+on: [workflow_dispatch, pull_request, push]
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
 jobs:
-  lint:
-    name: Commits - Lint
+  check:
+    name: Commits - Check
     runs-on: ubuntu-20.04
 
     # We assume that commit 2fd0d36fe6ae0c2d527368683ec3a6352617b381 will be in the history
     # of all commits based on ockam develop branch
     # https://github.com/ockam-network/ockam/commit/2fd0d36fe6ae0c2d527368683ec3a6352617b381
     env:
-      START_COMMIT_HASH: 2fd0d36fe6ae0c2d527368683ec3a6352617b381
+      FIRST_COMMIT: 2fd0d36fe6ae0c2d527368683ec3a6352617b381
 
     steps:
       - name: Checkout
-        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
+        if: github.event_name != 'pull_request'
+        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
         with:
           fetch-depth: 0 # checkout full tree
 
-      - name: Check START_COMMIT_HASH is ancestor of HEAD
+      - name: Checkout (Pull Request)
+        if: github.event_name == 'pull_request'
+        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
+        with:
+          fetch-depth: 0 # checkout full tree
+          ref: ${{ github.event.pull_request.head.sha }}
+
+      - name: Get commit information from Github (Pull Request)
+        if: github.event_name == 'pull_request'
+        run: gh api repos/ockam-network/ockam/pulls/${{ github.event.number }}/commits > commits.json
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Set FIRST_COMMIT (Pull Request)
+        if: github.event_name == 'pull_request'
+        run: echo "FIRST_COMMIT=$(cat commits.json | jq --raw-output '.[-1].sha')" >> $GITHUB_ENV
+
+      - name: Check all commits in are Verified by Github (Pull Request)
+        if: github.event_name == 'pull_request'
         run: |
-          git merge-base --is-ancestor $START_COMMIT_HASH HEAD || \
+          unverified=$(cat commits.json | jq --raw-output '.[] | [.sha, .commit.verification.verified] | @csv' | grep false || echo '')
+          if [ -z "$unverified" ]; then
+            echo '[✓] All commits in this pull request are Verified by Github.'
+          else
+            echo '
+              We require that all commits in a pull request are signed an Verified by Github
+
+              Please read about signing commits at:
+              https://docs.github.com/en/authentication/managing-commit-signature-verification
+
+              ERROR: The following commits are not Verified by Github.
+            '
+            echo "$unverified"
+            exit 1
+          fi
+
+      - name: Check FIRST_COMMIT is ancestor of HEAD
+        run: |
+          git merge-base --is-ancestor $FIRST_COMMIT HEAD || \
           (echo "
             This workflow checks that all commits follow the Ockam Commit Message Convention
             https://ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages
 
-            We check all commits from HEAD backwards till the commit with commit hash: ${START_COMMIT_HASH}.
+            We check all commits from HEAD backwards till the commit with commit hash: ${FIRST_COMMIT}.
 
             ERROR:
-            For this to work the commit with commit hash: ${START_COMMIT_HASH} should be an ancestor of HEAD
+            For this to work the commit with commit hash: ${FIRST_COMMIT} should be an ancestor of HEAD
             but it seems this is not the case with the current HEAD.
 
             Try rebasing to the develop branch of ockam.
             https://github.com/ockam-network/ockam/tree/develop
           " && exit 1)
 
+      - name: Check no merge commits
+        run: |
+          merge_commit_count=$(git rev-list --no-walk --count --merges $FIRST_COMMIT..HEAD)
+          if [ "$merge_commit_count" != "0" ]; then
+            echo "
+              Our develop branch follows a linear history and cannot have merge commits.
+              Please rebase to develop.
+            " && exit 1
+          fi
+
       - name: Install Commitlint
         run: npm install -g @commitlint/cli # TODO: move to ockam/builder docker image.
 
-      - name: Lint Commits
+      - name: Lint Commit Messages
         run: |
           npx commitlint \
             --config tools/commitlint/commitlint.config.js \
-            --from $START_COMMIT_HASH \
+            --from $FIRST_COMMIT \
             --to HEAD \
             --help-url https://www.ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages || \
             (echo '
@@ -78,3 +125,107 @@ jobs:
               More about the Ockam Commit Message Convention
               https://ockam.io/learn/how-to-guides/contributing/CONTRIBUTING#commit-messages
             ' && exit 1)
+
+      - name: Get Contributors List
+        run: |
+          curl --proto '=https' --tlsv1.2 --silent --show-error --fail \
+            https://raw.githubusercontent.com/ockam-network/contributors/main/CONTRIBUTORS.csv \
+            > CONTRIBUTORS.csv
+
+      - name: Split Contributors List
+        shell: python
+        run: |
+          import csv
+          import re
+          import sys
+
+          contributors_github_usernames = []
+          contributors_emails = []
+          email_pattern = re.compile("<([^>]+)>")
+
+          with open('CONTRIBUTORS.csv', 'r') as f:
+            reader = csv.reader(f)
+            # skip the first row of headers
+            next(reader)
+            for line in reader:
+              contributors_github_usernames = contributors_github_usernames + line[1].split()
+              contributors_emails = contributors_emails + email_pattern.findall(line[3])
+
+          with open('CONTRIBUTORS_GITHUB_USERNAMES.txt', 'w') as f:
+            print('\n'.join(contributors_github_usernames), file=f)
+
+          with open('CONTRIBUTORS_EMAILS.txt', 'w') as f:
+            print('\n'.join(contributors_emails), file=f)
+
+      - name: Check Pull Request Sender has accepted Ockam CLA.
+        if: github.event_name == 'pull_request'
+        env:
+          PR_SENDER: ${{ github.event.pull_request.user.login }}
+        run: |
+          if grep -q -F "$PR_SENDER" 'CONTRIBUTORS_GITHUB_USERNAMES.txt'; then
+            echo "[✓] Pull Request Sender $PR_SENDER has accepted the CLA."
+          else
+            echo "
+              $PR_SENDER, welcome to the Ockam community and thank you for sending this pull request ❤️.
+
+              Before we can merge, please accept our Contributor License Agreement (CLA).
+
+              1. Read the CLA at: https://www.ockam.io/learn/how-to-guides/contributing/cla
+
+              2. To accept the CLA, please send a different pull request to our
+              [contributors repository](https://github.com/ockam-network/contributors) indicating
+              that you accept the CLA by adding your Git/Github details in a row at the end of the
+              [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/main/CONTRIBUTORS.csv)
+              file.
+
+              We look forward to merging your first contribution!
+            "
+            exit 1
+          fi
+
+      - name: Check all commit authors and committers have accepted Ockam CLA.
+        run: |
+          commits=$(git rev-list --reverse $FIRST_COMMIT..HEAD)
+          commits=($FIRST_COMMIT ${commits[@]})
+          err=false
+
+          for commit in "${commits[@]}"
+          do
+            echo -e "\n---\nCommit: $commit"
+
+            author=$(git show -s --format='%ae' $commit)
+            echo "Author: $author"
+            committer=$(git show -s --format='%ce' $commit)
+            echo "Committer: $committer"
+
+            if grep -q -F "$author" 'CONTRIBUTORS_EMAILS.txt'; then
+              echo "[✓] $commit author $author has accepted the CLA."
+            else
+              echo -e "$commit commit author $author has not accepted the CLA."
+              err=true
+            fi
+
+            if grep -q -F "$committer" 'CONTRIBUTORS_EMAILS.txt'; then
+              echo "[✓] $commit committer $committer has accepted the CLA."
+            else
+              echo -r "\nERROR:\n$commit committer $committer has not accepted the CLA"
+              err=true
+            fi
+
+            if [ "$err" = true ]; then
+              echo "
+                Before we can merge, please accept our Contributor License Agreement (CLA).
+
+                1. Read the CLA at: https://www.ockam.io/learn/how-to-guides/contributing/cla
+
+                2. To accept the CLA, please send a different pull request to our
+                [contributors repository](https://github.com/ockam-network/contributors) indicating
+                that you accept the CLA by adding your Git/Github details in a row at the end of the
+                [CONTRIBUTORS.csv](https://github.com/ockam-network/contributors/blob/main/CONTRIBUTORS.csv)
+                file.
+
+                We look forward to merging your contribution!
+              "
+              exit 1
+            fi
+          done
